[package]
name = "solver"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
ac-library-rs = "0.1.1"
proconio = "0.5.0"
rand = "0.8.5"

[build-dependencies]
rustsourcebundler = { git = "https://github.com/lpenz/rust-sourcebundler" }
